defaults:
  - base

dataset:
  name: "mphoi72"
  root: "data/mphoi72/"
  num_classes: 13
  num_subjects: 12
  cross_validation: "two_subject_out"

  clip_subject: "person"
  clip_template: "A photo of a person {verb}"

model:
  num_classes: 13

training:
  epochs: 50
  batch_size: 1
  stage1_epochs: 3

  scheduler: "cosine"
